### ISSUE TITLE
JSON files not cooking in UE 5.2.1

### ISSUE THREAD

**Issue by DanGoesIntercept** [JonasReich/OUUJsonDataAssets#1]
Using Unreal Engine 5.2.1, I'm trying to cook and package JSON files that live in my `[Project Root]/Data` directory, but they don't make it into the packaged build. The trouble seems to be in `JsonDataAssetSubsystem.cpp`, line 1102:
```
TArray<FAssetIdentifier> Dependencies;
IAssetRegistry::Get()->GetDependencies(AssetIdentifier, OUT Dependencies);
```
`GetDependencies(...)` winds up not filling out any dependencies, even though all of the code above this is finding my JSON files successfully. Down in `AssetRegistryState.cpp`,  line 918, no "dependencies" are found for those JSON files:
```
const FDependsNode* const* NodePtr = CachedDependsNodes.Find(AssetIdentifier);
```
I'm thinking that this *should* be finding the assets that are linked to these JSON files, but for some reason they're not being found in `CachedDependsNodes` (maybe they're not being populated now in 5.2.1?).

By the way, fabulously helpful plugin, thank you!

**Comment by JonasReich** [comment]
Thanks for the report! Does this issue affect the json source files, dependency assets or both?
Also, which version do you currently use? In the current version https://github.com/JonasReich/OUUJsonDataAssets/commit/04c8656076216f43b6882f52cee5aa26bb9e1e63, dependencies are queried from the asset registry in line 1188 https://github.com/JonasReich/OUUJsonDataAssets/blob/04c8656076216f43b6882f52cee5aa26bb9e1e63/Source/OUUJsonDataRuntime/Private/JsonDataAssetSubsystem.cpp#L1188

I made some changes to the cooking logic relatively recently that recognize some of the built-in command line options for the regular cook (e.g. `-iterate` and `-NoDev`) that you'll probably want to have as well. Dependencies should be automatically included in the cook. unless you add the `-NoJsonDataDependencies` command line option.

The json source files themselves will need to be added to the packaging configuration in `DefaultGame.ini`

```ini
[/Script/UnrealEd.ProjectPackagingSettings]
+DirectoriesToAlwaysStageAsNonUFS=(Path="../CookedData")
```

I'll try to make this an implicit setting in the future, but so far I didn't find a good solution that takes the `ouu.JsonData.SourceCooked` console variable into account, so it's still a manual config step.

**Comment by JonasReich** [comment]
I just tested cooking behavior in a small isolated test case in https://github.com/JonasReich/OpenUnrealSampleProject/commit/c6384b694f003d12eb81322c0945713e6b27bd6b and found everything to work with a UE 5.2.1 engine installation.

In that sample, `Data/Tests/TestAsset_CookReferencer.json` pulls in `Content/Tests/BP_TestAsset_CookDependency_InCook.uasset` as a dependency, but `Content/Tests/BP_TestAsset_CookDependency_NotInCook.uasset` is correctly omitted from the cooked content.

**Comment by DanGoesIntercept** [comment]
Just so you don't close the issue yet -- I'll be back to this in short order, just got pulled in a different direction. Your quick response is much appreciated!

**Comment by JonasReich** [comment]
Closed: Cannot reproduce. Feel free to open another ticket with reproduction steps if this issue occurs again.
